version: '3.8'
services:
  nginx-back:
    restart: always
    image: nginx:1.20.1
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:${APP_DIRECTORY}
      - ./docker/nginx/backend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-back
  php-back:
    restart: always
    container_name: app_back
    build: ./docker/php
    volumes:
      - ./src:${APP_DIRECTORY}
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - pgsql
  pgsql:
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
      POSTGRES_DB: hackathon
    volumes:
      - ./docker/db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"